# Load libraries
```{r}
library(dplyr)
library(corrplot)
library(ggplot2)
library(svglite)
library(rethinking)
```

# Load data
```{r}
load("./data/data_r_in_num.RData")
```

# Exploring correlations in data
```{r}
dlist <- list(
      Population = as.numeric(d_in$Survey_population),
      Population_s = standardize(as.numeric(d_in$Survey_population)),
      Returned = as.numeric(d_in$Survey_returned),
      Returned_s = standardize(as.numeric(d_in$Survey_returned)),
      StudyPeriod = as.integer(d_in$study_period),
      Swedish = as.integer(d_in$Swedish),
      Overall_s = standardize(as.numeric(d_in$Overall)),
      Prereq_s = standardize(as.numeric(d_in$Prerequisites)),
      LearningOut_s = standardize(as.numeric(d_in$LearningOutcome)),
      Structure_s = standardize(as.numeric(d_in$CourseStruc)),
      Teaching_s = standardize(as.numeric(d_in$Teaching)),
      Literature_s = standardize(as.numeric(d_in$Literature)),
      Assessment_s = standardize(as.numeric(d_in$Assessment)),
      Admin_s = standardize(as.numeric(d_in$Admin)),
      Workload_s = standardize(as.numeric(d_in$Workload)),
      Equality_s = standardize(as.numeric(d_in$Equality)),
      Equality_bin = as.integer(d_in$InEquality_bin)
)
```

```{r}
model_moverall <- ulam(log_lik=TRUE,
      alist(
      Overall_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_w * Workload_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_mprereq <- ulam(log_lik=TRUE,
      alist(
      Prereq_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_w * Workload_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_mlearningout <- ulam(log_lik=TRUE,
      alist(
      LearningOut_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_w * Workload_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_mstruct <- ulam(log_lik=TRUE,
      alist(
      Structure_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_l * LearningOut_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_w * Workload_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_mteach <- ulam(log_lik=TRUE,
      alist(
      Teaching_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_w * Workload_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_mlit <- ulam(log_lik=TRUE,
      alist(
      Literature_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_a * Assessment_s + b_ad * Admin_s + b_w * Workload_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_massess <- ulam(log_lik=TRUE,
      alist(
      Assessment_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_ad * Admin_s + b_w * Workload_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_madmin <- ulam(log_lik=TRUE,
      alist(
      Admin_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_w * Workload_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2
)
```

```{r}
model_mwork <- ulam(log_lik=TRUE,
      alist(
      Workload_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_e * Equality_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_mequal <- ulam(log_lik=TRUE,
      alist(
      Equality_s ~ dnorm(mu, sigma),
      mu <- a[Swedish] + b_pop * Population_s + b_ret * Returned_s + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_w * Workload_s,
      a[Swedish] ~ dnorm(0, 1),
      b_pop ~ dnorm(0, 1),
      b_ret ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```


```{r}
model_mreturn <- ulam(log_lik=TRUE,
      alist(
      Returned ~ dbinom(Population, p),
      logit(p) <- a[StudyPeriod] + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_w * Workload_s + b_e * Equality_s,
      a[StudyPeriod] ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      sigma ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

```{r}
model_mtot <- ulam(log_lik=TRUE,
      alist(
      Overall_s ~ dnorm(mu, sigma),
      mu <- a_0 + b_p * Prereq_s + b_l * LearningOut_s + b_s * Structure_s + b_t * Teaching_s + b_li * Literature_s + b_a * Assessment_s + b_ad * Admin_s + b_e * Equality_s + b_w * Workload_s,
      Workload_s ~ dnorm(nu_w, tau_w),
      nu_w <- a_w + b_w_p * Prereq_s + b_w_s * Structure_s + b_w_t * Teaching_s + b_w_l * LearningOut_s,
      LearningOut_s ~ dnorm(nu_l, tau_l),
      nu_l <- a_l + b_l_t * Teaching_s,
      Equality_s ~ dnorm(nu_e, tau_e),
      nu_e <- a_e + b_e_t * Teaching_s + b_e_ad * Admin_s,
      Assessment_s ~ dnorm(nu_a, tau_a),
      nu_a <- a_a + b_a_t * Teaching_s,
      Teaching_s ~ dnorm(nu_t, tau_t),
      nu_t <- a_t + b_t_l * Literature_s,
      a_0 ~ dnorm(0, 1),
      a_w ~ dnorm(0, 1),
      a_l ~ dnorm(0, 1),
      a_e ~ dnorm(0, 1),
      a_a ~ dnorm(0, 1),
      a_t ~ dnorm(0, 1),
      b_p ~ dnorm(0, 1),
      b_w_p ~ dnorm(0, 1),
      b_l ~ dnorm(0, 1),
      b_t_l ~ dnorm(0, 1),
      b_w_l ~ dnorm(0, 1),
      b_s ~ dnorm(0, 1),
      b_w_s ~ dnorm(0, 1),
      b_t ~ dnorm(0, 1),
      b_l_t ~ dnorm(0, 1),
      b_e_t ~ dnorm(0, 1),
      b_a_t ~ dnorm(0, 1),
      b_w_t ~ dnorm(0, 1),
      b_li ~ dnorm(0, 1),
      b_a ~ dnorm(0, 1),
      b_ad ~ dnorm(0, 1),
      b_e_ad ~ dnorm(0, 1),
      b_e ~ dnorm(0, 1),
      b_w ~ dnorm(0, 1), 
      sigma ~ dexp(1),
      tau_w ~ dexp(1),
      tau_l ~ dexp(1),
      tau_e ~ dexp(1),
      tau_a ~ dexp(1),
      tau_t ~ dexp(1)
      ), data = dlist, chains = 2, cores = 2

)
```

## Saving the models so we do not have to re-run them all the time.
```{r}
save(model_moverall, model_mprereq, model_mlearningout, model_mstruct, model_mteach, model_mlit, model_massess, model_madmin, model_mwork, model_mequal, model_mreturn, file = "./data/model_real_out.RData")

## Exporting the data from the models for plotting in seaborn
data_moverall <- extract.samples(model_moverall)
data_mprereq <- extract.samples(model_mprereq)
data_mlearningout <- extract.samples(model_mlearningout)
data_mstruct <- extract.samples(model_mstruct)
data_mteach <- extract.samples(model_mteach)
data_mlit <- extract.samples(model_mlit)
data_massess <- extract.samples(model_massess)
data_madmin <- extract.samples(model_madmin)
data_mwork <- extract.samples(model_mwork)
data_mequal <- extract.samples(model_mequal)
data_mreturn <- extract.samples(model_mreturn)

save(data_moverall, data_mprereq, data_mlearningout, data_mstruct, data_mteach, data_mlit, data_massess, data_madmin, data_mwork, data_mequal, data_mreturn, file = "./data/modeldata_real_out.RData")
```


```{r}
load("./data/model_real_out.RData")
load("./data/modeldata_real_out.RData")
```

```{r}
precis(model_moverall, prob = 0.9, digits = 2)
precis(model_mprereq, prob = 0.9, digits = 2)
precis(model_mlearningout, prob = 0.9, digits = 2)
precis(model_mstruct, prob = 0.9, digits = 2)
precis(model_mteach, prob = 0.9, digits = 2)
precis(model_mlit, prob = 0.9, digits = 2)
precis(model_massess, prob = 0.9, digits = 2)
precis(model_madmin, prob = 0.9, digits = 2)
precis(model_mwork, prob = 0.9, digits = 2)
precis(model_mequal, prob = 0.9, digits = 2)
```